# ===== CONSTANTS =====
# GPIO PORTS FOR RGB LED
PWM_FREQUENCY					= 5000
MAX_DUTY_CYCLE					= 1023
DEFAULT_BRIGHTNESS_PERCENTAGE	= 10
RGB_LED_RED_GPIO				= 18
RGB_LED_GREEN_GPIO				= 19
RGB_LED_BLUE_GPIO				= 21

# LORA MODULE
LORA_UART_NUM           		= 2
LORA_UART_BAUD          		= 9600
